image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  # Cannot connect to the Docker daemon at tcp://docker:2375
  # https://gitlab.com/gitlab-org/gitlab-foss/issues/64959
  DOCKER_TLS_CERTDIR: ""

stages:
    - build
    - test
    - build-docker

build:
    stage: build
    script:
        - "cd DiscordBot/"
        - "dotnet restore"
        - "dotnet build"

test:
    stage: test
    script:
        - "cd DiscordBot/"
        - "dotnet restore"
        - "dotnet test"

build-docker:
  only:
    - master
  stage: build-docker
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY_URL
  script:
    - docker build -t $REGISTRY_URL/discord-meme-bot/bot:latest . -f ./DiscordBot/Dockerfile
    - docker push $REGISTRY_URL/discord-meme-bot/bot:latest
