version: "3.9"

services:
  bot:
    image: ${DOCKER_REGISTRY-}bot
    container_name: meme-bot
    restart: always
    build:
      context: .
      dockerfile: DiscordBot/Dockerfile
    depends_on:
        - redis
    environment:
      - Discord__Token=${DiscordToken}
  redis:
    image: redis
    container_name: meme-bot-cache
    expose:
      - 6379
